[package]
name = "frontend"
version = "0.1.0"
authors = ["Nick Senger <nicholas.senger@synthego.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fluorophore = { git = "https://github.com/nicksenger/fluorophore.git", branch = "dev/pin-moxie" }
futures = "^0.3.6"
graphql_client = "^0.9"
mox = { git = "https://github.com/anp/moxie.git", rev = "bd7b85f917cd976481e9e45719baab9fa74a782d" }
moxie = { git = "https://github.com/anp/moxie.git", rev = "bd7b85f917cd976481e9e45719baab9fa74a782d" }
moxie-dom = { git = "https://github.com/anp/moxie.git", rev = "bd7b85f917cd976481e9e45719baab9fa74a782d" }
moxie-streams = { git = "https://github.com/nicksenger/moxie-streams.git", branch = "dev/pin-moxie" }
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "^1", features = ["derive"] }
topo = { git = "https://github.com/anp/moxie.git", rev = "bd7b85f917cd976481e9e45719baab9fa74a782d" }
wasm-bindgen = "0.2.68"
wasm-bindgen-futures = "0.4.18"

[build-dependencies]
api-gateway = { path = "../api-gateway" }
juniper = { git = "https://github.com/graphql-rust/juniper" }
serde_json = "^1"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
