[package]
name = "frontend"
version = "0.1.0"
authors = ["Nick Senger <nicholas.senger@synthego.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fluorophore = { git = "https://github.com/nicksenger/fluorophore.git" }
futures = "^0.3.6"
mox = { git = "https://github.com/anp/moxie.git" }
moxie = { git = "https://github.com/anp/moxie.git" }
moxie-dom = { git = "https://github.com/anp/moxie.git" }
moxie-streams = { git = "https://github.com/nicksenger/moxie-streams.git" }
topo = { git = "https://github.com/anp/moxie.git" }
wasm-bindgen = "0.2.68"

[build-dependencies]
api-gateway = { path = "../api-gateway" }
juniper = { git = "https://github.com/graphql-rust/juniper" }
serde_json = "^1"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
