version: "3.7"
services:
  users-db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - 5432:5432
    volumes:
      - glot_users_db_volume:/var/lib/postgresql/data
  
  users-service:
    build:
      context: ./
      dockerfile: users.Dockerfile
    depends_on:
      - users-db
    ports:
      - 50051:50051
    env_file: users-service/.env

  api-gateway:
    build:
      context: ./
      dockerfile: gateway.Dockerfile
    environment:
      USERS_SERVICE_URI: http://users-service:50051
    depends_on:
      - users-service
    ports:
      - 8000:8000

volumes:
  glot_users_db_volume: