[package]
name = "schema"
version = "0.1.0"
authors = ["Nick Senger <dev@nsenger.com>"]
edition = "2018"

[dependencies]
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
tonic = "0.3"

[build-dependencies]
tonic-build = "0.3"
